export default {
  Address: "text",
  Boolean: "checkbox",
  ComboBox: "text",
  Currency: "number",
  Date: "text",
  DateTime: "text",
  Double: "number",
  Email: "email",
  Int: "number",
  Location: "text",
  MultiPicklist: "text",
  Percent: "text",
  Phone: "tel",
  Picklist: "text",
  String: "text",
  TextArea: "text",
  Time: "text",
  Url: "url",
};

//Base64: null,
//ComplexValue: "text",
//EncryptedString: "text",
//Reference: "text",
